hash-format = "sha256"

[[files]]
file = "config/alwaysmoreitems/config.yml"
hash = "2c13e1b61cc0514066ef0732cd53523985e4b91f65fae03026080721db45f333"

[[files]]
file = "config/betterf3.json"
hash = "d9c0e7c5355fab4f07dc01df6ca0e6b2bc8b9db4e80d8d1b59d9ce64a0f94c9c"

[[files]]
file = "config/freecam/config.yml"
hash = "e895407940aa1d9a6e885c485c2488703e52e91d1a8be06e65ab18212298bee5"

[[files]]
file = "config/hudtweaks/config.yml"
hash = "61ae4cededba0f4328aa9b5f59829d262de722f73c1526f8f4cae991443103ae"

[[files]]
file = "config/hudtweaks/hudpositions.yml"
hash = "42a84c55f9a673facf5d1e1ece38dab2cd4121bb4b4db11faf42b33f9ebafbe7"

[[files]]
file = "config/inventorytweaks/inventoryTweaks.yml"
hash = "1a6c36fe7d027b3edd0a602d915a4a8d3c1f40ce3457338af92e7ff3a899d608"

[[files]]
file = "config/macula/shaders.properties"
hash = "cc751c9cfbc4e3dab13c67521e8f91047bf1fa0efad7e7aaf674691ea8e5a460"

[[files]]
file = "config/misctweaks/config.yml"
hash = "276668778129f4d27d0e0836b82b78348659be40d0d4e1a3ed32ddf2c38f8db6"

[[files]]
file = "config/modmenu.json"
hash = "4257a25ec78b98ae66a01731303121cff4b87c851d092fc644c122b9896702d3"

[[files]]
file = "config/station-api-configuration/config.yml"
hash = "5f12c760bf980afa2cf6b331f4e87c884f5c6a36c99a0869bf5379b981c62b29"

[[files]]
file = "config/unitweaks/bugfixes.yml"
hash = "e572695e156e7bb51fa10a94d0433d0a0faaff65eb32cf7b0f1f20049fb570e4"

[[files]]
file = "config/unitweaks/features.yml"
hash = "81b24af0d2bdd517168accd453fc64682d828c5c63b6f1fd08875236dd39c5a7"

[[files]]
file = "config/unitweaks/gameplay.yml"
hash = "e256ebc77e6d3a2ffc07a69bd9a266d4a53a5815d54ccd21539f6a989ae780bd"

[[files]]
file = "config/unitweaks/general.yml"
hash = "128980ca597f29231bd351440352bfebe3ad3f7ea277bc8d0047b045aece7abf"

[[files]]
file = "config/unitweaks/oldfeatures.yml"
hash = "b52beb3305505fa7df100e7ef09390da8116c907044b85c7d58cef1014416cc0"

[[files]]
file = "config/unitweaks/recipes.yml"
hash = "0a560e4e1f5214f0ae9a6bbfcaba164c748042899d49257ea731f6d15641cb74"

[[files]]
file = "config/unitweaks/tweaks.yml"
hash = "545b77d52276098509c7909e2353a992be2a29f0bb8cc9d70c60a1eb6b2a3213"

[[files]]
file = "config/unitweaks/userinterface.yml"
hash = "2d2289a47d69e1148a21cecfb271b1fb5b165d4a59d7c956bc6b2c0c153f0f30"

[[files]]
file = "mods/AlwaysMoreItems-1.7.0.jar"
hash = "c3d0672987278b9113189e7b9760b204686401d3f95dede9e80116c530466c46"

[[files]]
file = "mods/BHCreative-0.4.9.jar"
hash = "b98173892b37f235b5a7db0ece1cd43508b42757fdb259bbddad7a03ca04dab0"

[[files]]
file = "mods/GlassConfigAPI-3.2.4.jar"
hash = "f98854a0ff1d915c38d25cf8aef6fb36a5b947dc18798d241fabf83ed4b82908"

[[files]]
file = "mods/HudTweaks-1.8.0.jar"
hash = "a62c6684cf8a5f7a0d766356ff369a0556609cb3f76a0216119765ac342a7bfb"

[[files]]
file = "mods/InventoryTweaks-2.5.2.jar"
hash = "b35746b1150ca1523ada68f24f0149158a87813b8dbddef69252349d1e161d31"

[[files]]
file = "mods/Macula-1.1.jar.disabled"
hash = "c2fe861a421db9d42c16de16e41fdec7331e4b5a6e5928aa3ff8376a295c4c21"

[[files]]
file = "mods/MiscTweaks-5.4.0.jar"
hash = "ed872d47d3cf067f7a4bf6059603d0b1ac48375ce6359ca70b7d0d3b29822a85"

[[files]]
file = "mods/SmoothBeta-1.1.7.jar"
hash = "c6646f3e3538e02789ed2c101bf98b332b6ab319259dd1d1be1e488fc3496b5f"

[[files]]
file = "mods/StationAPI-2.0.0-alpha.5.2.jar"
hash = "5b111d0a058e824180511ee2399c9a7695aa6320172efbc50d7605ba725cce29"

[[files]]
file = "mods/UniTweaks-0.22.2.jar"
hash = "cca4d95fcc7306e508bf0af3b7c8a0f664aabed395fbacf675bc6cd7611384fe"

[[files]]
file = "mods/accessoryapi.pw.toml"
hash = "5cd39e3dbf940580117bd2f220f83b762c0c6712460097b7d4a1a6adc62e5b56"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "537666f03ef62d5779bf4a03202edbd7931c90dc5b3792059ff1a2bc658d2ab3"
metafile = true

[[files]]
file = "mods/betterf3-0.5.3.jar"
hash = "7029e32533178789058260531523ad90eccca90d68b9cdf4806a6c141a00483c"

[[files]]
file = "mods/entity-culling-1.6.3.jar"
hash = "2db7251b132cc77e0c38bdb0b80c29d4ed609f95378c870e83e53130b85cec18"

[[files]]
file = "mods/freecam-0.3.2.jar"
hash = "f35c5b07ef0359d76f07d1ff5c1b4b8c32030e1fdbb6aca900f9e7b7326f7283"

[[files]]
file = "mods/gambac-1.3.0.jar"
hash = "e7908cd73404dd71482883ac56ce38e7c3d110855a40ddd42f211f58d8098d6b"

[[files]]
file = "mods/glass-networking-1.0.7.jar"
hash = "992190f8e7f904afe6e1e311ad17ea18c1c2ebced6dbee41a8a62b9723c3751d"

[[files]]
file = "mods/modmenu-1.0.1.jar"
hash = "efd2dd2e2e3b873dd34f4d771881e868adede01a44eac3fb632534391ffdd0e9"

[[files]]
file = "mods/retroauth-1.1.1.jar"
hash = "2d1b03e2e29625059aae5ad77828003b3a1680223049a856bc457a87c0c244b7"

[[files]]
file = "mods/retrocommands-0.5.10.jar"
hash = "b82604ed559bdd6c910206ab377e108330295c9841b58eaa0043c08f1aa5c99f"

[[files]]
file = "shaderpacks/SEUS v06.zip"
hash = "d148dc2875ce382ee528ce589abeafdb84b5bfc74b64512815656ab022711018"

[[files]]
file = "shaderpacks/SEUS v08.zip"
hash = "f79b268ecb25c17d5066d1612365eced3923761b0a09c5c9496d9bcfcc92e4ab"

[[files]]
file = "shaderpacks/SEUS v09 No Blur.zip"
hash = "f699ec136762b2fcf999268addf5c57312dde1da7a5729c7d8cc3fdf9fc50aee"

[[files]]
file = "shaderpacks/SEUS v09.zip"
hash = "e86f8bcfe511178356060886d2d0f117f87b7d7d87aaf8f9bfeca093863211be"

[[files]]
file = "shaderpacks/Vivians Shaders.zip"
hash = "ac740259aa1c640f2fb3267e312872114144b0c0deb18cc3dec9133eb9e5ae74"

[[files]]
file = "shaderpacks/World Curvature Shaders.zip"
hash = "46c7e03928b9269dc0db768771a423403d516d0efe8bd385cf576cc25d44e20f"
