name = "Babric Enriched"
author = "DanyGames2014"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d6ac1a15e19ee2fa9d4b442048cec843eb15378d8b0afc8e8d0945a38dac7a3"

[versions]
fabric = "0.17.2"
minecraft = "b1.7.3"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["b1.7.3"]
