name = "Babric Enriched"
author = "DanyGames2014"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89379f76d237c35115cb5351bedaa0439678fd887a4040cb6cfde8d245ddbc97"

[versions]
fabric = "0.17.2"
minecraft = "b1.7.3"
unsup = "1.2.0-pre1"

[options]
acceptable-game-versions = ["b1.7.3"]
