[flavor_groups.aether]
name = "Install Aether"
description = "Do you wish to install the Aether mod?"
side = "both"
[[flavor_groups.aether.choices]]
id = "aether_on"
name = "Yes"
description = "Install the Aether mod"
[[flavor_groups.aether.choices]]
id = "aether_off"
name = "No"
description = "Do not install the Aether mod"

[metafile.aether]
flavors = ["aether_on"]

[metafile.accessoryapi]
flavors = ["aether_on"]